# pull official base image
FROM node:16.20.0

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

# add app
COPY . ./

# Set Git configurations
RUN git config --global user.email "vinh94@hotmail.fr"
RUN git config --global user.name "Vinh Nguyen"

# Set the GitHub token as an environment variable
ENV GITHUB_TOKEN=$GITHUB_TOKEN

# Configure Git to use the GitHub token
RUN git config --global credential.helper '!f() { echo "password=$GITHUB_TOKEN"; }; f'


# start app
CMD ["npm", "run", "deploy"]

